### PR TITLE
Update all dependency references.

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Just a simple update to all reference dependencies. Might help with any .NET FX type forwarding issues

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
No idea what or why this is happening. Can get the tests to run locally without crashing either because ImageMagick decoder always crashes 

https://github.com/SixLabors/ImageSharp/runs/845593121?check_suite_focus=true#step:7:97

**Comment by JimBobSquarePants** [comment]
@antonfirsov I think we need to reevaluate our usage of `RemoteExecutor` to workaround some of the flakiness.

https://github.com/SixLabors/ImageSharp/runs/859311527?check_suite_focus=true#step:7:195

It does look like there's a way with Xunit to run code once at startup which would mean we could move it out of static contructors.
https://stackoverflow.com/a/53143426/427899

**Comment by antonfirsov** [comment]
@JimBobSquarePants the last test failure I see is because of Magic.NET. What if we revert updating that, and address it in a separate PR?

**Comment by antonfirsov** [comment]
Since it's a test-only change, I don't see a point to keep the 1.0 milestone.

**Comment by JimBobSquarePants** [comment]
I was going to update the .NET references also. I'll have one last crack in a mo but if that fails I'll scrap it.

**Comment by JimBobSquarePants** [comment]
@antonfirsov Turns out `System.Memory` is the trigger. I've updated all other .NET dependencies.

**Comment by JimBobSquarePants** [comment]
I'm just gonna go ahead and merge this now since there are no code changes.

**Pull request merged**
