### PR TITLE
Add LoadResizeSave benchmark

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
- Adding a LoadResizeSave benchmark aka. Bertrand Le Roy's golden standard for comparing image scaling solutions
- Adding EnableParallelExecution to Resize becnhmark, because it's an important parameter

This is part of a work updating the SixLabors documentation for beta5, and adding a new short article about ImageSharp performance.

### Benchmark Results

```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=2742188 Hz, Resolution=364.6723 ns, Timer=TSC
.NET Core SDK=2.1.300
  [Host]     : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  Job-ILXLYY : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
  Job-OSTKHA : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT

LaunchCount=1  TargetCount=3  WarmupCount=3

        Method | Runtime | EnableParallelExecution |      Mean |     Error |    StdDev | Scaled | ScaledSD |    Gen 0 | Allocated |
-------------- |-------- |------------------------ |----------:|----------:|----------:|-------:|---------:|---------:|----------:|
 SystemDrawing |     Clr |                   False |  67.78 ms | 10.615 ms | 0.5998 ms |   1.00 |     0.00 | 250.0000 | 791.07 KB |
    ImageSharp |     Clr |                   False | 188.16 ms | 43.288 ms | 2.4459 ms |   2.78 |     0.04 |        - |  51.59 KB |
               |         |                         |           |           |           |        |          |          |           |
 SystemDrawing |    Core |                   False |  69.32 ms |  5.249 ms | 0.2966 ms |   1.00 |     0.00 | 250.0000 | 789.79 KB |
    ImageSharp |    Core |                   False | 209.43 ms | 55.936 ms | 3.1605 ms |   3.02 |     0.04 |        - |  50.53 KB |
               |         |                         |           |           |           |        |          |          |           |
 SystemDrawing |     Clr |                    True |  68.51 ms | 19.667 ms | 1.1112 ms |   1.00 |     0.00 | 250.0000 | 791.07 KB |
    ImageSharp |     Clr |                    True |  93.63 ms |  9.225 ms | 0.5212 ms |   1.37 |     0.02 |        - |  58.59 KB |
               |         |                         |           |           |           |        |          |          |           |
 SystemDrawing |    Core |                    True |  68.34 ms | 21.592 ms | 1.2200 ms |   1.00 |     0.00 | 250.0000 | 789.79 KB |
    ImageSharp |    Core |                    True | 100.43 ms | 11.180 ms | 0.6317 ms |   1.47 |     0.02 |        - |  51.93 KB |
```

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
My only issue with this is that it's not really a fair comparison as long as we are premultiplying.

**Comment by tzachshabtay** [comment]
Shouldn't premultiplication be optional? I might load an image with alpha already premultiplied as part of my content pipeline, or I might want to premultiply in my shader.

**Comment by JimBobSquarePants** [comment]
@tzachshabtay I think it should move to options yes. It adds a lot of overhead.

**Comment by antonfirsov** [comment]
@JimBobSquarePants you're right, I think I will defer my detailed perf. article until we make premultiplication optional or maybe even until #642 is implemented.

Nevertheless, we can merge this, and extend the bechmark later, when the premultiplication switch is available.

**Comment by JimBobSquarePants** [comment]
Feel free to merge whenever

**Pull request merged**
