### PR TITLE
Update AllocatePaddedPixelRowBuffer to use IMemoryOwner<byte>

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Refactors `MemeoryAllocatorExtensions.AllocatePaddedPixelRowBuffer` to return `IMemoryOwner<byte>`.

Touches #1675

### CODE REVIEW

**Review by brianpopow — APPROVED** [review]

**Review by antonfirsov — APPROVED** [review]
Note that the whole purpose of `IManagedByteBuffer` is to avoid perf penalty on `<=netstandard2.1` coming from the buffer copy in the polyfilling methods. The idea is that any `MemoryAllocator` can implement `AllocateManagedByteBuffer` regardless of it's core logic, so strictly speaking it does not block switching to unmanaged allocators.

It's 2021 though, simplification of our codebase has higher priority than Framework performance, so I'm fine with the proposed change.

**Comment by JimBobSquarePants** [comment]
@antonfirsov how would you access the Array property of an unmanaged buffer? That was the original trigger for me making the change.

**Comment by antonfirsov** [comment]
@JimBobSquarePants you don't need to, because the returned buffer wouldn't be unmanaged. I mean: any allocator can return - for example - an array from `ArrayPool<byte>.Shared` in `.AllocateManagedByteBuffer`, even if the rest of it's allocators logic deals with unmanaged stuff. I know this is a bit counter-intuitive and ugly, but was the price paid of keeping Framework code optimal.

**Comment by JimBobSquarePants** [comment]
I think our wires are a little crossed here. What I meant was that returning an `IManagedByteBuffer<T>` for a type like like [`UnmanagedBuffer<T>`](https://github.com/SixLabors/ImageSharp/blob/547614acb19a9d3e2e2ab718844fb82f2aae3d8a/src/ImageSharp/Memory/Allocators/Internals/UnmanagedBuffer%7BT%7D.cs) was impossible (_I think_) since there would be nothing to populate the `IManagedByteBuffer<T>.Array` property. This would mean we would be maintaining two separate memory allocation processes. 

I'm happy to make the performance sacrifice for Framework since the overarching benefit of an optimized allocator will outweigh a few ms in the codecs.

**Pull request merged**
