### PR TITLE
Fix small deviation to the spec when encoding tiff images

### LINKED ISSUE #2297: created/overwritten/copied TIFF images are invalid for Adobe Premiere Pro
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

SixLabors.ImageSharp 2.1.3, SixLabors.ImageSharp.Drawing 1.0.0-beta14, SixLabors.Fonts 1.0.0-beta17

### Environment (Operating system, version and so on)

Windows Server 2019 Standard 1809

### .NET Framework version

.Net 6.0, .Net Framework 4.8

### Description

Tiff files created by ImageSharp are not recognized by Adobe Premiere Pro on any try of import.
If you try to import a tiff file an error will pop up: "The file cannot be opened because of a header error"
If you take a tiff file created by ImageSharp, open it with Paint or Adobe Photoshop and save it without any changes, choosing TIFF format, Importing files to Premiere Pro becomes possible.
It seems there is an issue, when encoding the tiff image by ImageSharp since other software can save the image in format properly. I could not find any differences in metadata that would indicate which parameter is invalid.

### Steps to Reproduce

`using Image<Rgba32> image = new(1920, 1080);`
`using MemoryStream stream = new();`
`image.SaveAsTiff(output);`

### Images

Premiere Pro error

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR fixes the following issues when encoding tiff images:
- Write padding byte, because the tiff spec requires ifd offset to begin on a word boundary.
- Change samples per pixel to ushort

Closes #2297

### CODE REVIEW

**Review by JimBobSquarePants — APPROVED** [review]
LGTM 👍

**Comment by brianpopow** [comment]
There is a failing test, I am trying to figure out if it is a regression introduced with this changes, but I dont know how yet.

**Comment by JimBobSquarePants** [comment]
I’ll have a poke at it later.

**Comment by JimBobSquarePants** [comment]
@brianpopow There appears to be a corrupted EXIF value in the encoded output. Unknown tag of type byte[] with two entries at the beginning with the rest empty.

image

**Comment by brianpopow** [comment]
The input image metadata_sample.tiff already seems to be completely broken:

```
identify: Unknown field with tag 18246 (0x4746) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 18249 (0x4749) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40091 (0x9c9b) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40092 (0x9c9c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40093 (0x9c9d) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40094 (0x9c9e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40095 (0x9c9f) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 59932 (0xea1c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: IO error during reading of "Tag 40095"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/950.
identify: F:\vsprojekte\ImageSharp.Playground\tests\Images\Input\Tiff\metadata_sample.tiff: Can not read TIFF directory. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/597.
identify: Failed to read custom directory at offset 5596. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/597.
identify: Unknown field with tag 18246 (0x4746) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 18249 (0x4749) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40091 (0x9c9b) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40092 (0x9c9c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40093 (0x9c9d) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40094 (0x9c9e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 40095 (0x9c9f) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: Unknown field with tag 59932 (0xea1c) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/950.
identify: IO error during reading of "Tag 40095"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/950.
```

I will try to fix that first.

**Comment by brianpopow** [comment]
Ok the input file is fixed now. I assume the error in the encoded EXIF profile came from the corrupted input file.

**Review by JimBobSquarePants — APPROVED** [review]

**Pull request merged**
