### PR TITLE
Add BuildJet ARM64 runners.

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

I've signed up for an ARM64 runner via BuildJet. 

https://buildjet.com/for-github-actions/docs/runners#which-runner-should-i-use

Fingers crossed this works out-of-the-box as documentation is light.

### CODE REVIEW

**Review by brianpopow — APPROVED** [review]

**Comment by JimBobSquarePants** [comment]
@brianpopow got some failing stuff here. Seems System.Drawing related. Will need to make some additional changes. Anything obvious you can think of from your PR?

**Comment by brianpopow** [comment]
> @brianpopow got some failing stuff here. Seems System.Drawing related. Will need to make some additional changes. Anything obvious you can think of from your PR?

mhm I first thought all the runner were green. It looks like libgdi+ dependency is missing. Should be easy to add, I will take a look.

**Comment by JimBobSquarePants** [comment]
@brianpopow I had to do a bit more work to get everything green. Everything checks out now though and I've manually verified all output.

**Comment by brianpopow** [comment]
@JimBobSquarePants I tried to run the tests on my ARM device and had `BmpDecoder_CanDecode_Os2BitmapArray` failing. Turns out the testfiles did have upper case file-endings. This was causing them not being treated as binary files from git-lfs. I am not sure why this only fails on my device, though. Fixed now with 3fd4fdc0

**Review by brianpopow — APPROVED** [review]
I think this is ready now for merging, glad we can now finally test on ARM.

**Pull request merged**
