### PR TITLE
Prevent text wandering from baseline

### LINKED ISSUE #685: Wrapped text "wandering" from baseline on successive lines.
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Wrapped text appears to "wander" on successive "wraps"

### Steps to Reproduce
Following code:

``` c#
public static void DrawWrappedText()
{
    Console.WriteLine($"Executing {System.Reflection.MethodBase.GetCurrentMethod().Name}");

    // White filled "4 x 6" (if measured as 200 DPI).
    Image<Rgba32> TestImage = new Image<Rgba32>(800, 1200);
    TestImage.Mutate(x => x.Fill(Rgba32.White));

    // Font F = SystemFonts.CreateFont("Arial", 30, FontStyle.Regular);
    Font F = SystemFonts.CreateFont("Baskerville Old Face", 30, FontStyle.Regular);

    string T = "’Twas brillig, and the slithy toves Did gyre and gimble in the wabe: All mimsy were the borogoves, And the mome raths outgrabe.\"Beware the Jabberwock, my son!  The jaws that bite, the claws that catch!  Beware the Jubjub bird, and shun The frumious Bandersnatch!\"";

    TextGraphicsOptions TGO = new TextGraphicsOptions(true)
    {
        WrapTextWidth = TestImage.Width
    };

    TestImage.Mutate(x => x.DrawText(TGO, T, F, Rgba32.Black, new PointF(10, 50)));

    TestImage.Save("WrappedText.jpg");


}
```
Produced the following:

wandering-text

Zoom into the 4th line of text.  The characters are "wandering" vertically off the baseline.

1st line seems OK, and each successive line seems to get "worse".

Other fonts tried (Arial), but the Baskerville shows issue clearly.,

### System Configuration

- ImageSharp version: 1.0.0-beta0005
- Other ImageSharp packages and versions: SixLabors.ImageSharp; SixLabors.ImageSharp.Drawing
- Environment (Operating system, version and so on): Win10; Visual Studio 2017 v 15.8.0
- .NET Framework version: .Net Core 2.1
- Additional information:

### PR DESCRIPTION
**Pull request by tocsoft**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

this fixes #685 

The issue was the fact we where being to aggressive when caching rendered/repeated glyphs.

We now should be allowing approx 4 slightly offset variants of a single glyph (+/- 1 pixel on both axis).

### before
before image with wandering text

### after
after with baseline fixed

### CODE REVIEW

**Comment by tocsoft** [comment]
@antonfirsov feel free to tweek the tolerances... I never get the level them right.

The reason I made the tolerances exact was because the sample FontShapesAreRenderedCorrectly_LargeText.png did show the issue (its just more prominent with the other font)... 'tis why I needed to update the reference image too now I had resolved the problem.

**Comment by JimBobSquarePants** [comment]
> @antonfirsov feel free to tweek the tolerances... I never get the level them right.

I commented about this in Gitter the other week. I find the tolerance comparer confusing. 

Current the default threshold is `3.921569E-07` calculated as `((1 / 255F) * 65535) / (100 * 100 * 65535)` which is defined as

 _1% of all pixels in a 100*100 pixel area are allowed to have a difference of 1 unit_ 

That's amazing technically that we can calculate this but far too complicated to use. 

I want to simply pass something like 2% and if the image is more than 2% different then it fails.

**Comment by JimBobSquarePants** [comment]
@antonfirsov Ok that makes more sense!

**Comment by antonfirsov** [comment]
@JimBobSquarePants actually, we can simplify the comparison and the way we parameterize it by rebasing it on scaled `Vector4` pixel values.

**Comment by tocsoft** [comment]
Differences are fine and expected... It's differences that effect the visual baseline that are the problem... Which is something that is nigh on impossible to quantify and test for.

**Comment by antonfirsov** [comment]
@tocsoft if we allow higher differences with `AccuracyMultiple = 2` the "wandering" is visually well visible on the output images (check the images in my comment). 

The smaller the reported difference is, the more correct the output feels, so I think the difference ratio is a good quantitative value to benchmark output correctness.

**Comment by antonfirsov** [comment]
Or maybe I'm missing the point of your comment? 😕

**Comment by tocsoft** [comment]
That's strange because with a 2 it wasn't wandering on my machine... Odd  yeah 8 is fine then... I believe it's going to be one of those tweek the settings as/if people complain that it's still happening.

**Comment by JimBobSquarePants** [comment]
Is the error a point of origin calculation issue?

**Comment by antonfirsov** [comment]
Anything against merging this now?

**Pull request merged**
