### PR TITLE
Webp encoder now defaults to lossy, if nothing else is specified

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

To match `libwebp` behavior, the Webp encoder now defaults to lossy, if nothing else is specified.

### CODE REVIEW

**Review by JimBobSquarePants — APPROVED** [review]
LGTM 👍

**Comment by JimBobSquarePants** [comment]
@brianpopow I'm seeing a lack of alpha channel support when using lossy encoding. Is that expected?

**Comment by PhyxionNL** [comment]
Until alpha support is added, I'm not sure this is a good default as you'd end up with lots of broken images.

**Comment by brianpopow** [comment]
I am working on alpha encoding. Should not take too long to implement.

**Comment by JimBobSquarePants** [comment]
@brianpopow HERO!

**Pull request merged**
