### PR TITLE
Fix adaptive histogram out of bounds bug

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR fixes an ArrayOutOfBound Exception issue which occurs in some cases with the adaptive histogram interpolation. It happens because in some cases the tile start position array is calculated one entry too large.

This happens for example when the image width is 990 and height is 750. With 10 tiles this makes a ```tileHeight``` of 99. Half tile width would be 49 then, which leads to a wrong termination condition of the for loop which calculates the start positions.

### CODE REVIEW

**Comment by antonfirsov** [comment]
I wonder if we can provide a regression test with input smaller than `990 x 750`?

**Comment by brianpopow** [comment]
> I wonder if we can provide a regression test with input smaller than `990 x 750`?

@antonfirsov  I could make a test which resizes an existing image to some image sizes were i know this issue happens and then run the histogram equalization and assert in the end that no exception is thrown. Would that be sufficient?

An alternative could be that i add an additional image to the ReferenceOutput which has a image size which triggers this issue and make an additional test similar to the already existing histogram tests: [HistogramTests](https://github.com/SixLabors/ImageSharp/blob/master/tests/ImageSharp.Tests/Processing/Normalization/HistogramEqualizationTests.cs)

**Comment by antonfirsov** [comment]
[`[WithBasicTestPatternImages]`](https://github.com/SixLabors/ImageSharp/blob/aac8eae64aab06ecd8aa0210e49fb0ba67e9a4ea/tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs#L85) is what you need in such cases.

**Comment by antonfirsov** [comment]
@brianpopow I think it's also useful to validate the output, not just the fact that exception is not thrown. As a first step, I pushed a change `DebugSave()`-ing the image.

For 110x110 it looks like this, which doesn't seem correct to me:
Issue984_Rgba32_TestPattern110x110

**Comment by antonfirsov** [comment]
I'm merging this as-is, so we can release beta7.

**Comment by brianpopow** [comment]
@antonfirsov i will look into this and provide a better test, as soon as possible.

**Pull request merged**
