### PR TITLE
WIP: Png decoder fix for Issue #1014

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR fixes an issue when decoding PNG where data would spread over multiple IDAT chunks.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Oh wow! Amazing! I was so worried about those issues.

Thanks so much for helping out here, it’s really really appreciated!

**Comment by brianpopow** [comment]
@JimBobSquarePants maybe at the end of the Issue1014 unit test a `image.CompareToOriginal(provider, ImageComparer.Exact);` could be added, just to make sure.

**Comment by antonfirsov** [comment]
Yeah definitely, let's always include validating tests in all PR-s!

**Comment by JimBobSquarePants** [comment]
Yes, missed that it wasn’t there in my excitement!

**Pull request merged**
