### PR TITLE
show "using" statement in example

### PR DESCRIPTION
**Pull request by chrischip**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### CODE REVIEW

**Comment by antonfirsov** [comment]
@chrischip can you [register the email address associated your first commit](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) on GitHub?

@JimBobSquarePants is it possible to dismiss CLAassistant for this PR?

**Comment by chrischip** [comment]
This is exactly the problem i am facing.... sorry I tried hours can
couldn't figure out where the first "Chris" commit credential came from. I
don't even know which email address is associated with that. I am using
VSCode but I've get a few Git credential for work and another one for
GitLab and some of them have private key for ssh and some don't. This is
first time I try to request for a PR for a public Github still not sure
where all these credentials came from.....

**Comment by JimBobSquarePants** [comment]
I’ll try and temporarily turn it off.

**Comment by tocsoft** [comment]
you can just update the previous commits and fix the author email address and do a force push to get the changes back up

https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by JimBobSquarePants** [comment]
Closing in favour of #706 as it's easier to add a new PR than mess about with git and CLA signing.

Thanks @chrischip for your contribution 👍

**Pull request closed without merging**
