### PR TITLE
WIP #12 Refactory tiff structures, decoder classes

### PR DESCRIPTION
**Pull request by IldarKhayrutdinov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [ ] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [ ] I have provided test coverage for my change (where applicable)

### Description

Deep refactoring and improves for tiff classes. 
And:
* Synch with master.
* Support multi framing.
* Using Metadata\Profiles\Exif\ types instead their duplicate tag types (moved to __obsolete directory).
* Implement useful Metadata classes.
* Add extensions.
* Test coverage.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
I think something went horribly wrong with the [`tiff-codec`](https://github.com/SixLabors/ImageSharp/tree/9773e61c92bfbe66ef6b21b7640685dc48423202) branch when this PR #986 was merged.

We won't be able to continue as-is as it's now impossible to update the branch from master without issues. 

I've created a new [`tiff`](https://github.com/SixLabors/ImageSharp/tree/d08c1917cfa2a12da0cb217a9461aaad3a4d7527) branch containing all the existing development but based upon the current master. 

If you can please apply your changes to the relevant files to a fork based upon that branch we'll be able to review them and continue.

Sorry for the inconvenience.

**Comment by IldarKhayrutdinov** [comment]
@JimBobSquarePants @antonfirsov  Yeah, this brunch is too far behind the master ... thanks for the help 😌

**Comment by JimBobSquarePants** [comment]
I see you've marked this ready for review but we cannot review and merge it in it's current state. 

I suggest, instead, that you close this PR and create a new one based upon the [branch](https://github.com/SixLabors/ImageSharp/tree/d08c1917cfa2a12da0cb217a9461aaad3a4d7527) I provided.

**Comment by IldarKhayrutdinov** [comment]
> I see you've marked this ready for review but we cannot review and merge it in it's current state.
> 
> I suggest, instead, that you close this PR and create a new one based upon the [branch](https://github.com/SixLabors/ImageSharp/tree/d08c1917cfa2a12da0cb217a9461aaad3a4d7527) I provided.

@JimBobSquarePants sorry, it was by chance, I preparing a new PR

**Comment by JimBobSquarePants** [comment]
@IldarKhayrutdinov Awesome! 👍

**Comment by IldarKhayrutdinov** [comment]
@antonfirsov @JimBobSquarePants as discussed in gitter, I create new PR https://github.com/SixLabors/ImageSharp/pull/1330 and I close this PR

**Pull request closed without merging**
