### PR TITLE
Remove return value documentation for void return types.

### PR DESCRIPTION
**Pull request by wischi-chr**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Very minor code documentation fixes.

### CODE REVIEW

**Review by dlemstra — APPROVED** [review]
Tnx for fixing this for us.

**Comment by JimBobSquarePants** [comment]
Needs to be fixed at the template level.

https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/ImageExtensions.Save.tt

**Comment by wischi-chr** [comment]
Should I change it only in the template or in both files?

**Comment by dlemstra** [comment]
Both files should be changed.

**Comment by wischi-chr** [comment]
The patch now includes the fix in the template as well.

**Pull request merged**
