### PR TITLE
Use compile time constants over method for all MMShuffle operations. 

### LINKED ISSUE #2121: Vector{128,256} operations that use MmShuffle fall back to method call
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

Current main branch

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

all .NET supported

### .NET Framework version

all

### Description

While working on https://github.com/SixLabors/ImageSharp/issues/1762 I recognized that methods that use https://github.com/SixLabors/ImageSharp/blob/c661ab1478419004271a1bd2281f5d4e478840b9/src/ImageSharp/Common/Helpers/SimdUtils.Shuffle.cs#L236-L238 won't emit platform-intrinsics, rather fallback to a method call as the value isn't a constant.

E.g. `Vp8Encoding.FTransformPass1SSE2` looks after inlining the vector constants like
```asm
       push      rdi
       push      rsi
       push      rbx
       sub       rsp,60
       vzeroupper
       xor       eax,eax
       mov       [rsp+50],rax
       mov       [rsp+58],rax
       mov       rsi,rdx
       mov       rdi,r8
       mov       rbx,r9
       vmovupd   xmm0,[rcx]
       lea       rcx,[rsp+40]
       vmovapd   [rsp+30],xmm0
       lea       rdx,[rsp+30]
       mov       r8d,0B1
       call      System.Runtime.Intrinsics.X86.Sse2.ShuffleHigh(System.Runtime.Intrinsics.Vector128`1<Int16>, Byte)
       vmovupd   xmm0,[rsi]
       lea       rcx,[rsp+50]
       vmovapd   [rsp+30],xmm0
       lea       rdx,[rsp+30]
       mov       r8d,0B1
       call      System.Runtime.Intrinsics.X86.Sse2.ShuffleHigh(System.Runtime.Intrinsics.Vector128`1<Int16>, Byte)
       vmovapd   xmm0,[rsp+40]
       vpunpcklqdq xmm0,xmm0,[rsp+50]
       vmovapd   xmm1,[rsp+40]
       vpunpckhqdq xmm1,xmm1,[rsp+50]
       vpaddw    xmm2,xmm0,xmm1
       vpmaddwd  xmm3,xmm2,[7FF7D3640A20]
       vpmaddwd  xmm2,xmm2,[7FF7D3640A30]
       vpsubw    xmm0,xmm0,xmm1
       vpmaddwd  xmm1,xmm0,[7FF7D3640A40]
       vpaddd    xmm1,xmm1,[7FF7D3640A50]
       vpsrad    xmm1,xmm1,9
       vpmaddwd  xmm0,xmm0,[7FF7D3640A60]
       vpaddd    xmm0,xmm0,[7FF7D3640A70]
       vpsrad    xmm0,xmm0,9
       vpackssdw xmm0,xmm1,xmm0
       vpackssdw xmm1,xmm3,xmm2
       vpunpcklwd xmm2,xmm1,xmm0
       vpunpckhwd xmm0,xmm1,xmm0
       vpunpckhdq xmm1,xmm2,xmm0
       vpunpckldq xmm0,xmm2,xmm0
       vmovupd   [rdi],xmm0
       mov       rcx,rbx
       vmovapd   [rsp+20],xmm1
       lea       rdx,[rsp+20]
       mov       r8d,4E
       call      System.Runtime.Intrinsics.X86.Sse2.Shuffle(System.Runtime.Intrinsics.Vector128`1<Int32>, Byte)
       nop
       add       rsp,60
       pop       rbx
       pop       rsi
       pop       rdi
       ret
; Total bytes of code 245
```
If instead `SimdUtils.Shuffle.MmShuffle` the constant is given as literal, then the code boils down to:
```asm
       vzeroupper
       vpshufhw  xmm0,[rdx],0B1
       vpshufhw  xmm1,[rcx],0B1
       vpunpcklqdq xmm2,xmm1,xmm0
       vpunpckhqdq xmm0,xmm1,xmm0
       vpaddw    xmm1,xmm2,xmm0
       vpmaddwd  xmm3,xmm1,[7FF7D365DAC0]
       vpmaddwd  xmm1,xmm1,[7FF7D365DAD0]
       vpsubw    xmm0,xmm2,xmm0
       vpmaddwd  xmm2,xmm0,[7FF7D365DAE0]
       vpaddd    xmm2,xmm2,[7FF7D365DAF0]
       vpsrad    xmm2,xmm2,9
       vpmaddwd  xmm0,xmm0,[7FF7D365DB00]
       vpaddd    xmm0,xmm0,[7FF7D365DB10]
       vpsrad    xmm0,xmm0,9
       vpackssdw xmm0,xmm2,xmm0
       vpackssdw xmm1,xmm3,xmm1
       vpunpcklwd xmm2,xmm1,xmm0
       vpunpckhwd xmm0,xmm1,xmm0
       vpunpckhdq xmm1,xmm2,xmm0
       vpunpckldq xmm0,xmm2,xmm0
       vmovupd   [r8],xmm0
       vpshufd   xmm0,xmm1,4E
       vmovupd   [r9],xmm0
       ret
; Total bytes of code 127
```

This is a de-facto a JIT-limitation, recorded in https://github.com/dotnet/runtime/issues/9989 and https://github.com/dotnet/runtime/issues/38003, also noticed in https://github.com/SixLabors/ImageSharp/pull/1517#discussion_r562059328

As this is quite a difference in code-gen, hence in perf it should show up too, I propose to change to typing the shuffle literals explicetely. E.g.
```diff
-Vector128<short> shuf01_p = Sse2.ShuffleHigh(row01, SimdUtils.Shuffle.MmShuffle(2, 3, 0, 1));   // or any similar pattern
+Vector128<short> shuf01_p = Sse2.ShuffleHigh(row01, 0xB1);  // MmShuffle(2, 3, 0, 1)
```

---

If OK I'd like to tackle this in one shot with https://github.com/SixLabors/ImageSharp/issues/1762 (as I'm touching these pieces anyway).
Edit: I was too eager, the PR is out...

### Steps to Reproduce

Look at dissassembly of any method that uses `SimdUtils.Shuffle.MmShuffle`.

### Images

_No response_

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #2121 

Ratios do seem to be better for Avx and Sse operations.

CC @gfoidl @tannergooding

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
This is super useful coming in .NET 8!

image

**Review by tannergooding — APPROVED** [review]

**Comment by stefannikolei** [comment]
It seems that this PR gives me some issues.

I tried to execute the tests after this PR and over 1000 failed.
I checked out an commit before this PR and all tests went green.

I am seeing those Exception:

```
LoadResizeSave [SKIP]
[xUnit.net 00:00:05.77]       Profiling benchmark, enable manually!
[xUnit.net 00:00:05.93]     BulkShuffle4Slice3Channel(count: 4) [FAIL]
[xUnit.net 00:00:05.93]       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
[xUnit.net 00:00:05.93]       Stack Trace:
[xUnit.net 00:00:05.93]         
[xUnit.net 00:00:05.93]         Child exception:
[xUnit.net 00:00:05.93]           System.ArgumentOutOfRangeException: Value 156 must be greater than or equal to 0 and less than or equal to 3. (Parameter 'control')
[xUnit.net 00:00:06.07]         /Users/stefannikolei/projects/github/sixlabors/ImageSharp/shared-infrastructure/src/SharedInfrastructure/DebugGuard.cs(279,0): at SixLabors.DebugGuard.ThrowArgumentOutOfRangeException(String parameterName, String message)
[xUnit.net 00:00:06.07]         /Users/stefannikolei/projects/github/sixlabors/ImageSharp/shared-infrastructure/src/SharedInfrastructure/DebugGuard.cs(151,0): at SixLabors.DebugGuard.MustBeBetweenOrEqualTo[TValue](TValue value, TValue min, TValue max, String parameterName)
[xUnit.net 00:00:06.07]         /Users/stefannikolei/projects/github/sixlabors/ImageSharp/src/ImageSharp/Common/Helpers/Shuffle/IShuffle4Slice3.cs(19,0): at SixLabors.ImageSharp.DefaultShuffle4Slice3..ctor(Byte control)
[xUnit.net 00:00:06.07]         /Users/stefannikolei/projects/github/sixlabors/ImageSharp/tests/ImageSharp.Tests/Common/SimdUtilsTests.Shuffle.cs(459,0): at SixLabors.ImageSharp.Tests.Common.SimdUtilsTests.<BulkShuffle4Slice3Channel>g__RunTest|41_0(String serialized)
```

My environment: 

```
SixLabors.ImageSharp.Tests: BenchmarkDotNet=v0.13.0, OS=macOS 13.2.1 (22D68) [Darwin 22.3.0]
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.200
  [Host] : .NET 6.0.14 (6.0.1423.7309), X64 RyuJIT
```

**Comment by JimBobSquarePants** [comment]
You’re right! It’s a debug guard. Thanks!

**Comment by JimBobSquarePants** [comment]
Have pushed a fix in #2369

**Comment by stefannikolei** [comment]
> Have pushed a fix in #2369 

Perhaps a good idea to run the tests in the CI pipeline in Debug mode?

**Comment by JimBobSquarePants** [comment]
We’d maybe run a single entry in the matrix. I wouldn’t run more than that as it gets expensive. We want to preserve our release mode ones also to ensure we catch jit issues

**Pull request merged**
