### PR TITLE
Fixed string exif value corner case exception

### PR DESCRIPTION
**Pull request by br3aker**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Closes https://github.com/SixLabors/ImageSharp/issues/2087.

Given image from linked issue contains empty user comment tag which is written last. Allocated buffer is passed as `Span` which is sliced during different exif values rendering to the given buffer. This exact situation led to copying zero bytes to zero-length span aaaaand looks like .net treats empty spans with valid memory pointer as null pointer thus mentioned `ArgumentNullException`.

Fix is fairly simple: use spans instead of working with raw pointers without any fixed statements (love this performance side effect) and unsafe stuff, `Encoding.GetBytes(ReadOnlySpan, Span)` respects empty spans.

~~P.S.
Waiting for issue image usage approval from the issue author.~~

### CODE REVIEW

**Comment by br3aker** [comment]
@JimBobSquarePants can you please advice where should I place the image from this issue?
I don't see any similar tests.

**Comment by antonfirsov** [comment]
@br3aker I think adding yet another entry to [BaselineTestJpegs](https://github.com/SixLabors/ImageSharp/blob/e54219acec10d2d2dc247ed5fd4230204a89c07b/tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs#L12) or [ProgressiveTestJpegs](https://github.com/SixLabors/ImageSharp/blob/e54219acec10d2d2dc247ed5fd4230204a89c07b/tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs#L50) is good enough, we have a bunch of Exif regression tests there already.

**Comment by JimBobSquarePants** [comment]
Yep, just add it to the collection there

**Comment by br3aker** [comment]
Problem is that this image decodes correctly, it throws on encoding during writing exif profile.

**Comment by JimBobSquarePants** [comment]
It’s cool, we did the same here. 

https://github.com/SixLabors/ImageSharp/pull/2059

**Comment by br3aker** [comment]
Done, hope I got your idea right.

**Review by JimBobSquarePants — APPROVED** [review]
Looks perfect. Thanks 👍

**Pull request merged**
