### PR TITLE
Add "macos-latest" to build matrix

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Just noticed there is an available [virtual environment](https://github.com/actions/virtual-environments) for macOS. I think we should add it to the list of CI builds.

### CODE REVIEW

**Comment by antonfirsov** [comment]
How can we add this to the list of Required checks?

**Comment by JimBobSquarePants** [comment]
In the branch protection settings.

**Comment by antonfirsov** [comment]
Woops 65 failing tests, this will be a bit harder than I naively thought.

Most of them are rooted in `libgdiplus` being missing for some reason. But there are many tests failing because of over-threshold differences in the output. There are two resize tests failing with 18% and 25% difference which may indicate an actual bug.

[macOS-Failure.log](https://github.com/SixLabors/ImageSharp/files/5017373/macOS-Failure.log)

**Comment by JimBobSquarePants** [comment]
They’re transform tests I think, not resize ones.

**Comment by brianpopow** [comment]
> In the branch protection settings. You should have access but if not, I’ll do it
> 
> Looks like we’re missing libgdiplus on the Mac OS. No idea how to add it

could this do the trick? 

```
- name: Install macos dependencies
  if: matrix.os == 'macos-latest'
  run: brew install mono-libgdiplus
```

**Comment by antonfirsov** [comment]
@brianpopow the condition did not evaluate to `true` somehow.

**Comment by brianpopow** [comment]
> @brianpopow the condition did not evaluate to `true` somehow.

@antonfirsov i cannot spot why that is, looks correct.

**Comment by antonfirsov** [comment]
Looks like it has been moved to `matrix.options.os` .

**Comment by antonfirsov** [comment]
29 test failures:
- 3 test code compatibility issues
- 2 of them likely indicating a macOS-only bug in padded resize
- The rest: accuracy issues, mostly in the range of `0.1% - 0,.9%`. (Reminds me of our 32 bit Framework accuracy issues.)

**Comment by JimBobSquarePants** [comment]
The padded resize bugs are interesting. Not sure how that happens...

Transforms I’ll never be 100% happy with, could be the perfectionist in me but the edges never looked quite right to me. Not as crisp as imagemagick.

**Comment by antonfirsov** [comment]
Doesn't make sense to keep around a stale PR, closing this in favor of #1387.

**Pull request closed without merging**
