### PR TITLE
Add new Color parsing methods.

### LINKED ISSUE #1103: Add Color.FromHtml
It would be extremely useful for migration from `System.Drawing` to this library to have the `FromHtml` equivalent.
The `FromHtml` takes a string which can be a color name or hex string and converts it to the relevant color.
As a side note, there are 3.5 million downloads to this library, I think it can be released instead of being a pre-release...
Can also be called `Color.FromString`.

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
- Adds `Color.TryParse`
- Adds `Color.Parse`
- Adds `Color.TryParseHex`
- Renames `Color.FromHex` to `Color.ParseHex`
- Adds `Rgba32.TryParseHex`
- Renames `Rgba32.FromHex` to `Rgba32.ParseHex`

`Color.TryParse` and `Color.Parse` recognize both color names and hexadecimal representation as per CSS4 specification in ordinal casing.  Fix #1103

<strike>I haven't added `Rgba32.TryParse` and `Rgba32.Parse` as I'm very tempted to drop the `Rgba32` named colors. I'd much rather channel color creation through the `Color` struct only. 

Please let me know if you agree that this is the best course of action.</strike>

EDIT. I went ahead and deleted them. Much happier now.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
@SixLabors/core Any objections to this. I'll add it tonight otherwise.

**Comment by brianpopow** [comment]
> @SixLabors/core Any objections to this. I'll add it tonight otherwise.

i have looked trough the changes. Looks good to me, i think it can be merged.

**Comment by jespersh** [comment]
Is this the commit that broke examples that use like?:
```C#
image.Mutate(x => x.BackgroundColor(Rgba32.White));
```
I suppose the replacement is just using `Color.White` instead?

**Comment by JimBobSquarePants** [comment]
There’s nothing broken, this is by design. `Color` is the correct pixel agnostic way to declare colors.

**Comment by jespersh** [comment]
I didn't say it was broken, I said it broke the examples :smile:

**Comment by JimBobSquarePants** [comment]
Which examples are broken? I’ll update if we own them.

**Comment by jespersh** [comment]
I followed this path to here:
https://stackoverflow.com/a/60642706
https://github.com/SixLabors/ImageSharp/issues/355#issuecomment-333133991

Thanks for this library.

**Comment by JimBobSquarePants** [comment]
@jespersh no worries! yeah, that's all out of date. We've got API docs https://docs.sixlabors.com/ that will be much more useful.

**Pull request merged**
