### PR TITLE
Bitmap decoder now can decode bitmap arrays

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR adds to the bitmap decoder the ability to decode Bitmap Arrays. Bitmap array files are typically used to hold multiple resolution bitmaps of the same image. The first image in the array will be decoded.
For more info see: [Bitmap Array](http://www.fileformat.info/format/bmp/egff.htm)

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
@brianpopow Wow. You've been busy! 

Is there an application that supports this variant that you know of I can use to compare the output with?

**Comment by brianpopow** [comment]
@JimBobSquarePants yes i had some spare time and i thought i could follow my quest in supporting all bitmap formats :smile:. We are getting close. 

The only program i know is gimp which can decode those images.

**Comment by JimBobSquarePants** [comment]
@brianpopow  I checked everything against Gimp and it all looks great! Thanks again for this! 👍

**Comment by brianpopow** [comment]
@JimBobSquarePants you are welcome!

I think i understand now how ColorIcon, ColorPointer, Icon and Pointer bitmaps can be decoded as well. They are a bit weird though, especially ColorIcon, ColorPointer. They contain two Bitmap info headers and therefore two bitmaps which need to be combined into one.

I thought it would be nice to support all valid bitmaps, even if they are ancient and not common anymore. Before i continue with that i wanted to ask you what you think about this. Does it make sense to support those old formats? I do not want to force something on you, which you may not want. Its totally fine with me, if you say that this old stuff is too weird, to be supported.

**Comment by JimBobSquarePants** [comment]
If you're happy to do the work then I'm happy to accept the enhancements. 😄

**Pull request merged**
