### PR TITLE
#244 Add support for interlaced PNG encoding

### PR DESCRIPTION
**Pull request by IldarKhayrutdinov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Implement Adam7 encoding algorithm for PNG format.

See: #244 
https://en.wikipedia.org/wiki/Adam7_algorithm

### CODE REVIEW

**Comment by IldarKhayrutdinov** [comment]
@JimBobSquarePants Please confirm 
_> I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules policeman.
> I have provided test coverage for my change (where applicable)_
and review the request.

**Comment by JimBobSquarePants** [comment]
@IldarKhayrutdinov Love it! I'll give all this a thorough review as soon as possible. Thanks for your help! 👍

**Comment by IldarKhayrutdinov** [comment]
@JimBobSquarePants FYI
My previous build (of 58bbc54) completed with a strange error, I didn’t find a rebuild button, I made a fake commit (47afe84).

For more see: https://ci.appveyor.com/project/six-labors/imagesharp/builds/26504296/job/qu4k3ct51w80rnvh
```
   SixLabors.ImageSharp.Tests  Total: 12246, Errors: 0, Failed: 0, Skipped: 15, Time: 62.206s
   Error uploading artifact the storage: One or more errors occurred.
```

**Comment by JimBobSquarePants** [comment]
@IldarKhayrutdinov Sometimes AppVeyor can be a shade unreliable but we can usually retrigger the build and get it running again. 

Your PR is next on my list to review (Which I'm sure will be very short, your code at first glance looks excellent!). 

Just a heads up though that I'm merging #951 once it builds which might cause some minor code conflicts in the Png encoder (likely formatting changes) so we might not be able to automatically update your feature branch from master.

**Comment by IldarKhayrutdinov** [comment]
@JimBobSquarePants Thanks! After merging #951 I will review my branch and work with conflicts.

**Comment by JimBobSquarePants** [comment]
@IldarKhayrutdinov I'll do the merge as part of my code review so hold tight for now.

**Comment by IldarKhayrutdinov** [comment]
@JimBobSquarePants Oh thanks, I haven't had time to do, but you already did ☺ I was happy to contribute!

**Pull request merged**
