### PR TITLE
Fix issue when writing lossy webp with alpha data

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix for issue #2171: The alpha chunk data was written completely (the size of the image in pixels) and not only the compressed data when writing a lossy webp image.

### CODE REVIEW

**Comment by brianpopow** [comment]
There are new failing tests with .Net7.0, this time on macos only. 222 are failing:

```
Error Message:
   System.PlatformNotSupportedException : Operation is not supported on this platform.
  Stack Trace:
     at System.Runtime.Intrinsics.Vector256.Create(Single value)
   at SixLabors.ImageSharp.Formats.Jpeg.Components.FastFloatingPointDCT.<IDCT8x8_Avx>g__IDCT8x8_1D_Avx|16_0(Block8x8F& block) in /_/src/ImageSharp/Formats/Jpeg/Components/FastFloatingPointDCT.Intrinsic.cs:line 141
   at SixLabors.ImageSharp.Formats.Jpeg.Components.Decoder.JpegComponentPostProcessor.CopyBlocksToColorBuffer(Int32 spectralStep) in /_/src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegComponentPostProcessor.cs:line 70
```

**Comment by JimBobSquarePants** [comment]
That’s concerning. @tannergooding sorry to page but are there changes coming to .NET 7 we should know about?

**Comment by tannergooding** [comment]
`System.Runtime.Intrinsics.Vector256.Create(Single value)` should work on all platforms, it might just not be accelerated on certain ones (x64 machines without AVX and Arm64 machines in general).

Do you have a simple repro? I don't immediately see any changes to the .NET 7 version or to any code newly using `Vector256` in this PR.

**Comment by brianpopow** [comment]
> `System.Runtime.Intrinsics.Vector256.Create(Single value)` should work on all platforms, it might just not be accelerated on certain ones (x64 machines without AVX and Arm64 machines in general).
> 
> Do you have a simple repro? I don't immediately see any changes to the .NET 7 version or to any code newly using `Vector256` in this PR.

Hi @tannergooding. I am not 100% sure if this will be enough, but from the error messages in this [CI run](https://github.com/SixLabors/ImageSharp/runs/7322478738?check_suite_focus=true) I would assume just calling:

```
var scale = Vector256.Create(200.0f);
```

on a Mac should be enough to trigger this. Since I do not have a Mac, I cannot verify that.
@JimBobSquarePants Maybe you have a chance to test, if that is indeed enough?

**Comment by tannergooding** [comment]
This might be an issue specifically around a machine with `AVX` but no `AVX2` support. I'll see if I can get a repro

**Comment by JimBobSquarePants** [comment]
Thanks @tannergooding I've been unable to reproduce this on my old 2.7 GHz Dual-Core Intel Core i5

**Comment by JimBobSquarePants** [comment]
I got some environmental info via #2175 

I'm at a loss to explain the cause.

```
OS=macOS Big Sur 11.6.7 (20G630) [Darwin 20.6.0]
Intel Xeon CPU E5-1650 v2 3.50GHz (Max: 3.34GHz), 1 CPU, 3 logical and 3 physical cores
.NET SDK=7.0.100-preview.6.22352.1
[Host] : .NET 7.0.0 (7.0.22.32404), X64 RyuJIT
```

**Comment by brianpopow** [comment]
> I got some environmental info via #2175
> 
> I'm at a loss to explain the cause.
> 
> ```
> OS=macOS Big Sur 11.6.7 (20G630) [Darwin 20.6.0]
> Intel Xeon CPU E5-1650 v2 3.50GHz (Max: 3.34GHz), 1 CPU, 3 logical and 3 physical cores
> .NET SDK=7.0.100-preview.6.22352.1
> [Host] : .NET 7.0.0 (7.0.22.32404), X64 RyuJIT
> ```

I think Tanner is on the right track with his guess that it's maybe related to a machine with AVX but not AVX2. Intel Xeon CPU [E5-1650](https://ark.intel.com/content/www/de/de/ark/products/64601/intel-xeon-processor-e51650-12m-cache-3-20-ghz-0-0-gts-intel-qpi.html) only has AVX from what I can tell.

**Comment by JimBobSquarePants** [comment]
>Maybe we can workaround these issues to get back clean CI until there is an upstream fix? We can disable Avx path on .NET7 when Avx2.IsSupported == false.

You mean for this instance? I think we're just hitting this one cos it comes first. We use `Vector256.Create(single)` in a few places. Theoretically we could turn off the support by setting the correct environmental variable during CI but I think I'd rather just disable .NET 7 Mac tests for now.

**Comment by tannergooding** [comment]
Ok, I can reproduce the issue and will work on getting a fix up.

**Comment by JimBobSquarePants** [comment]
AWESOME!

**Comment by antonfirsov** [comment]
> I'd rather just disable .NET 7 Mac tests for now.

Yeah, makes sense.

**Comment by tannergooding** [comment]
@JimBobSquarePants, the issue discussed above should be fixed as of https://github.com/dotnet/runtime/pull/72522 and will land in .NET 7 RC1.

-- Also, sorry for the ping after this has been closed for two weeks; wasn't sure of a better place to relay this small note.

**Comment by JimBobSquarePants** [comment]
@tannergooding That's fantastic news, thanks for letting me know. 

That's a very interesting conversation regarding AVX/AVX2 issues. I wonder if any of that is causing our NaN handling issues in #2117 . I've struggled to find the specs for Intel Xeon Platinum 8272CL

**Pull request merged**
