### PR TITLE
Fix issue in PNG identify method to skip "uninteresting" chunks, incl…

### PR DESCRIPTION
**Pull request by flew2bits**
…uding sBIT.

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [X] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [X] I have provided test coverage for my change (where applicable)

### Description
Add a default clause in the PNG Identify method to skip over "uninteresting" chunks so that the data is properly read. 
This fixes issue #2018

### CODE REVIEW

**Comment by flew2bits** [comment]
The call to SkipChunkDataAndCrc was in the wrong location to fix the problem. I've moved it to a location that should fix the problem.

**Comment by flew2bits** [comment]
I moved the call to SkipChunkDataAndCrc back to the default switch clause based on how other chunks are handled in the switch statement. It's not wrapped in a check to see if the identification is for color metadata only, also based on other clauses.

**Comment by brianpopow** [comment]
I have found an png with a sBit chunk:
length_sbit

Would that reproduce the described issue in #2018? If so, it would be good to have  a unit test covering this issue. See [PngDecoderTests](https://github.com/SixLabors/ImageSharp/blob/92da254bb8203ea5eb2fc8f58f849f487921466e/tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs#L246) for an example howto do that.

**Comment by flew2bits** [comment]
Unfortunately that image doesn't exhibit the problem. I'll see if I can put one together that can be used for testing.

**Comment by JimBobSquarePants** [comment]
I'm actually happy to push this in without the offending image. As a performance optimization alone it's worth the addition. 

@flew2bits if you could supply an image at some point that would be really great.

**Comment by JimBobSquarePants** [comment]
@brianpopow Yeah... Let's get it merged now.

**Pull request merged**
