### PR TITLE
#2807 Add early return in InternalDetectFormat

### PR DESCRIPTION
**Pull request by stefannikolei**
Added the early return in this method when a format is found.

### CODE REVIEW

**Review by JimBobSquarePants — APPROVED** [review]
Lovely. Thanks!

**Comment by antonfirsov** [comment]
A test would be nice for this to formalize the behavioral requirement.

**Comment by stefannikolei** [comment]
> A test would be nice for this to formalize the behavioral requirement.

Sure. Would you mind helping me? Perhaps point me in the right direction?

**Comment by JimBobSquarePants** [comment]
You’d have to make a test decoder that has a matching set of criteria as an existing one and test to ensure the correct decoder is returned based on the registration order.

**Pull request merged**
