### PR TITLE
Support another variant of BMP headers

### PR DESCRIPTION
**Pull request by mormegil-cz**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

ImageSharp did not support BMP images using the most primitive variant of the file header, the 12-byte `BITMAPCOREHEADER`. Files using this format ended on `throw new NotSupportedException("Does not support this kind of bitmap files.");`

This pull requests adds the support for such files. An example of such a file (generated using the `QRCoder` library, which is how I found the problem) is included in the test files, plus a new test class added to ensure all BMP files are tested. (Not sure if this is correct, feel free to improve.)

### CODE REVIEW

**Comment by antonfirsov** [comment]
Woops ... that merge was accidental, thought I'm commiting to your branch @mormegil-cz :confused: 

Anyways I tried the code, and it worked and looked good to me, so hope you don't mind this @JimBobSquarePants. (AppVeyor failed to do it's job again though.)

@mormegil-cz  thanks for your contribution! :)

**Comment by JimBobSquarePants** [comment]
@antonfirsov Looks good to me, only thing would be the [array allocation](https://github.com/SixLabors/ImageSharp/pull/302/files#diff-714cb6840484d8286614a88b6ab44e2aR373) when reading the header. 

Can't bump AppVeyor now that the PR is merged though. No idea what is causing the build to sometimes fail, it always works when bumped.

@mormegil-cz Really appreciate this! 👍

**Comment by antonfirsov** [comment]
@JimBobSquarePants that array is only 40 bytes in size, and it's allocated only once per decoder execution, doesn't worth to bother with pools and buffers in such cases.

Already merged this into #299. Another chance for AppVeyor to fight it's post-eclipse depression :P

**Comment by JimBobSquarePants** [comment]
@antonfirsov teeny tiny then, yeah not worth the overhead. Everything is building in #299 👍

**Pull request merged**
