### PR TITLE
Removed invalid check reported in issue #394.

### LINKED ISSUE #394: ImageFormatException: 'Bad Th value' on jpeg image
Hi,

I have a problem loading a specific jpeg image using ImageSharp.  The code is in an ASP.Net MVC Core application, and is loading the image data from an IFormFile stream.
The image is available at the following url:

[http://www.edenamps.com/images/eden_terra_nova_10-crop-u182927.jpg](http://www.edenamps.com/images/eden_terra_nova_10-crop-u182927.jpg)

Are you able to see if there's any way to get this to work?
We're loading the image to get the dimensions, and then creating a thumbnail from it.  If we load, then resave the image in Paint.Net, it works fine, but we'd like to know if there is a way to process the original image, in case we find more with the same encoding issue.

Thanks,

Jon

- ImageSharp version:  v1.0.0-beta0002
- Environment:  Windows 10 Pro (running under IISExpress)
- .NET Framework version: .Net Core v2.0.3

### PR DESCRIPTION
**Pull request by dlemstra**
Fixes #394

### CODE REVIEW

**Comment by J0nKn1ght** [comment]
Thanks for this fix.  Do you have any information on when this is likely to be included in a release?

**Comment by JimBobSquarePants** [comment]
@J0nKn1ght it'll be available in the nightlies right now if you add the myget endpoint in the read me to your Nuget.config.

**Comment by antonfirsov** [comment]
@dlemstra I added a test-case for this in #397.

**Comment by dlemstra** [comment]
Looks fine to me, cannot merge on my phone because the codecov is "lower"

**Comment by JimBobSquarePants** [comment]
Codecov is doing this a lot just now. Very frustrating, a rebuild always fixes it.

**Comment by J0nKn1ght** [comment]
@JimBobSquarePants Thanks - I tried looking at the nightlies, but the last one on myget is from 17th November, and so obviously doesn't include this fix.
Am I missing something?

**Comment by JimBobSquarePants** [comment]
@J0nKn1ght There's something wrong with our CI server build numbering. The latest build is actually 

https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp/1.0.0-ci0026

We'll get the numbers sorted asap.

**Comment by J0nKn1ght** [comment]
@JimBobSquarePants That works great. Thanks for all of your help.

**Comment by JimBobSquarePants** [comment]
No worries 😄

**Pull request merged**
