### PR TITLE
naming corrections - macOS and .NET

### PR DESCRIPTION
**Pull request by mikeirvingweb**
Naming corrections to macOS and .NET

**Written** (comments, debug comments, readme etc) ...

renamed:

- MacOSX -> macOS
- MacOs -> macOS
- OSX -> macOS
- .Net -> .NET

**Code** ...

renamed:

- IsNotMacOs -> IsNotMacOS
- InvokeMacOSX -> InvokeMacOS
- TestEnvironment.IsOSX -> TestEnvironment.IsMacOS

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Sorry @mikeirvingweb I just broken your PR by merging in a change from main that still referenced the old naming. Would you be able to update your end? Thanks!

**Comment by mikeirvingweb** [comment]
Ah, ok, no worries.. I was just trying to work out what was going on with
it :)

**Review by mikeirvingweb — COMMENTED** [review]
correction to repair breaking change from another merge

**Comment by JimBobSquarePants** [comment]
Thanks for the naming fixes!

**Pull request merged**
