### PR TITLE
Fix documentation of HorizontalResolution and VerticalResolution properties

### PR DESCRIPTION
**Pull request by 0xced**
Also improve the formatting of the ResolutionUnits documentation.

### CODE REVIEW

**Review by JimBobSquarePants — APPROVED** [review]
Ah JUST missed the V2 release.... 

This looks great, much appreciated 👍

**Comment by 0xced** [comment]
Too bad I just missed the v2 release!

I noticed this documentation glitch while porting the ClosedXML library from `System.Drawing` to ImageSharp (https://github.com/ClosedXML/ClosedXML/issues/1694#issuecomment-1031590337). Except for this small glitch the migration is going pretty smoothly. It's really a pleasure to work with such a well engineered and well documented library. 😍

**Comment by JimBobSquarePants** [comment]
Thanks! That's really great to hear!

Just had a very quick look at the port. You've got a mix of the old and new major versions of ImageSharp, Drawing, and, Fonts going on there which won't work well. I'm gonna be pushing new betas for both Fonts and Drawing today which will bring some changes (massive improvements) around text rendering. I'd strongly recommend bumping to a minimum of net472 also due the the [redirect issues with older targets](https://nickcraver.com/blog/2020/02/11/binding-redirects/)

**Comment by 0xced** [comment]
Actually, Drawing is not used. Nevertheless, I updated Fonts to the latest beta (16) and it was a matter of updating `IFontCollection.Install` to `IFontCollection.Add`, `IReadOnlyFontCollection.Find` to `IReadOnlyFontCollection.Get` and `RenderOptions` to the new `TextOptions`.

> I'd strongly recommend bumping to a minimum of net472 also due the the [redirect issues with older targets](https://nickcraver.com/blog/2020/02/11/binding-redirects/)

I'm fully aware of the issues with .NET Standard 2.0 *theoretically* supporting .NET Framework 4.6.1 but *actually* only supporting .NET Framework 4.7.2. But in such a large pull request, I prefer te be conservative with the changes to the target framework in order to focus on the rest of the pull request.

**Pull request merged**
