### PR TITLE
Ensure Span length of source and destination are equal during pixel conversion

### PR DESCRIPTION
**Pull request by brianpopow**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

As reported in #1442, there are some failing tests in the master branch. The reason for this is a `Debug.Guard` which ensures the span length are equal during pixel conversion. Sometimes the source span was smaller the the destination. This got unnoticed during **Release** CI runs.

### CODE REVIEW

**Review by antonfirsov — APPROVED** [review]
LGTM.

**Comment by antonfirsov** [comment]
> The reason for this is a `Debug.Guard` which ensures the span length are equal during pixel conversion. 

This shouldn't be the case, the `PixelOperations` contract allows `destination` to be longer. @JimBobSquarePants looks like `SimdUtils.Shuffle*` does a strict verification, which is fine (modeled after the `Vector4` conversion stuff I guess), but we should slice down `destination` in `PixelOperations` then.

**Comment by JimBobSquarePants** [comment]
Aha! I actually had to do a hack to allow for this in a debug check. 

https://github.com/SixLabors/ImageSharp/commit/1ad9fcdad63259ee628b04c81b85108e9948bbfb#diff-ba27a760948c3e593e3ac6a18ad7b8ea04bc0255376575088b7fad70814040e3R227-R231

I'll be able to set it right.

**Comment by brianpopow** [comment]
i will leave this as it is now. Maybe someone should give a quick review of 7c77e7e11cd49c39e057523aa0147bf0ae6cccff again

**Review by JimBobSquarePants — APPROVED** [review]
LGTM 👍

**Pull request merged**
