### PR TITLE
WIP: #12 Synch with master and improve performance of decoders

### PR DESCRIPTION
**Pull request by IldarKhayrutdinov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [ ] I have provided test coverage for my change (where applicable)

### Description

* merge from master
* add simple blackBox tests and benchmarks for decoder
* report deflate decoding bug (see: 51720a8cea3eb559c1c743109b04baeadaaf5c07)
* improve performance of decoders at 1.1x - 2.5x (see: 1b32629e30c13fe7e27afec1cfefbb3d13198bb9)

### CODE REVIEW

**Comment by antonfirsov** [comment]
@Sergio0694 can you help a bit? Doest the bokeh blur processor + test code look up to date on this branch?

**Comment by James-Jackson-South** [comment]
@antonfirsov @Sergio0694 I can have a look, I'm familiar with that code also now.

**Comment by IldarKhayrutdinov** [comment]
@antonfirsov Thanks! Really I forgot to update submodules :smiley:
@antonfirsov @James-Jackson-South @Sergio0694 @Andy-Wilkinson Now I have passed the tests locally and I expect that on the CI will pass. Please code review.

**Comment by Sergio0694** [comment]
Thanks @James-Jackson-South!
@antonfirsov I think James is actually more familiar than me with the tests part of the bokeh blur processor actually, as he kindly set that part up after I finished working on the last tweaks for the processor itself 😄

**Comment by JimBobSquarePants** [comment]
1198 files! Crikey! 

I'll do a folder check via BeyondCompare before digging through the diff. Everything should be identical except for the new Tiff code.

**Comment by IldarKhayrutdinov** [comment]
> 1198 files! Crikey!
> 
> I'll do a folder check via BeyondCompare before digging through the diff. Everything should be identical except for the new Tiff code.

Sure, the most of changes are merge from master.

**Comment by antonfirsov** [comment]
@James-Jackson-South since this is not going into `main`, I think we can merge it as-is as soon as the tests in `TiffDecoderTests` are matching the current capabilities of the decoder.

I see a few improvement points, but I don't think it's a good idea to address them in this huge PR, let's do them later:
- Using `MemoryAllocator` and disposable buffers instead of `ArrayPool.Shared`
- Consider sharing code with other decoders. Eg. `TiffLzwDecoder` looks pretty much the same as `SixLabors.ImageSharp.Formats.Gif.LzwDecoder`

**Comment by antonfirsov** [comment]
@James-Jackson-South see #988 for the diff.

**Comment by JimBobSquarePants** [comment]
Thanks, I’ll have a look later today. :+1:

**Comment by JimBobSquarePants** [comment]
Looks good to me. Will merge now.

**Pull request merged**
