### PR TITLE
Save as extensions

### PR DESCRIPTION
**Pull request by pekspro**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
This add several methods for saving images. Id addresses #1255.

There were no unit test for the existing extensions so I did not ceate anyone for this either. But I did make sure that all extensions for all file formats produced identical files with this code:

    using SixLabors.ImageSharp;
    using System;
    using System.IO;
    using System.Threading.Tasks;

    namespace ConsoleAppImageSharpTester
    {
        class Program
        {
            static async Task Main(string[] args)
            {
                var img = Image.Load(@"testimage.png");

                Directory.CreateDirectory(@".\test");

                {
                    img.SaveAsTga(@".\test\norm_name.tga");
                    img.SaveAsTga(@".\test\norm_name_enc.tga", new SixLabors.ImageSharp.Formats.Tga.TgaEncoder());
                    await img.SaveAsTgaAsync(@".\test\async_name.tga");
                    await img.SaveAsTgaAsync(@".\test\async_name_enc.tga", new SixLabors.ImageSharp.Formats.Tga.TgaEncoder());
                    using var f1 = new FileStream(@".\test\norm_stream.tga", FileMode.OpenOrCreate);
                    img.SaveAsTga(f1);
                    using var f2 = new FileStream(@".\test\norm_stream_enc.tga", FileMode.OpenOrCreate);
                    img.SaveAsTga(f2, new SixLabors.ImageSharp.Formats.Tga.TgaEncoder());
                    using var f3 = new FileStream(@".\test\async_stream.tga", FileMode.OpenOrCreate);
                    await img.SaveAsTgaAsync(f3);
                    using var f4 = new FileStream(@".\test\async_stream_enc.tga", FileMode.OpenOrCreate);
                    await img.SaveAsTgaAsync(f4, new SixLabors.ImageSharp.Formats.Tga.TgaEncoder());
                }

                {
                    img.SaveAsPng(@".\test\norm_name.png");
                    img.SaveAsPng(@".\test\norm_name_enc.png", new SixLabors.ImageSharp.Formats.Png.PngEncoder());
                    await img.SaveAsPngAsync(@".\test\async_name.png");
                    await img.SaveAsPngAsync(@".\test\async_name_enc.png", new SixLabors.ImageSharp.Formats.Png.PngEncoder());
                    using var f1 = new FileStream(@".\test\norm_stream.png", FileMode.OpenOrCreate);
                    img.SaveAsPng(f1);
                    using var f2 = new FileStream(@".\test\norm_stream_enc.png", FileMode.OpenOrCreate);
                    img.SaveAsPng(f2, new SixLabors.ImageSharp.Formats.Png.PngEncoder());
                    using var f3 = new FileStream(@".\test\async_stream.png", FileMode.OpenOrCreate);
                    await img.SaveAsPngAsync(f3);
                    using var f4 = new FileStream(@".\test\async_stream_enc.png", FileMode.OpenOrCreate);
                    await img.SaveAsPngAsync(f4, new SixLabors.ImageSharp.Formats.Png.PngEncoder());
                }
            

                {
                    img.SaveAsBmp(@".\test\norm_name.bmp");
                    img.SaveAsBmp(@".\test\norm_name_enc.bmp", new SixLabors.ImageSharp.Formats.Bmp.BmpEncoder());
                    await img.SaveAsBmpAsync(@".\test\async_name.bmp");
                    await img.SaveAsBmpAsync(@".\test\async_name_enc.bmp", new SixLabors.ImageSharp.Formats.Bmp.BmpEncoder());
                    using var f1 = new FileStream(@".\test\norm_stream.bmp", FileMode.OpenOrCreate);
                    img.SaveAsBmp(f1);
                    using var f2 = new FileStream(@".\test\norm_stream_enc.bmp", FileMode.OpenOrCreate);
                    img.SaveAsBmp(f2, new SixLabors.ImageSharp.Formats.Bmp.BmpEncoder());
                    using var f3 = new FileStream(@".\test\async_stream.bmp", FileMode.OpenOrCreate);
                    await img.SaveAsBmpAsync(f3);
                    using var f4 = new FileStream(@".\test\async_stream_enc.bmp", FileMode.OpenOrCreate);
                    await img.SaveAsBmpAsync(f4, new SixLabors.ImageSharp.Formats.Bmp.BmpEncoder());
                }

                {
                    img.SaveAsGif(@".\test\norm_name.gif");
                    img.SaveAsGif(@".\test\norm_name_enc.gif", new SixLabors.ImageSharp.Formats.Gif.GifEncoder());
                    await img.SaveAsGifAsync(@".\test\async_name.gif");
                    await img.SaveAsGifAsync(@".\test\async_name_enc.gif", new SixLabors.ImageSharp.Formats.Gif.GifEncoder());
                    using var f1 = new FileStream(@".\test\norm_stream.gif", FileMode.OpenOrCreate);
                    img.SaveAsGif(f1);
                    using var f2 = new FileStream(@".\test\norm_stream_enc.gif", FileMode.OpenOrCreate);
                    img.SaveAsGif(f2, new SixLabors.ImageSharp.Formats.Gif.GifEncoder());
                    using var f3 = new FileStream(@".\test\async_stream.gif", FileMode.OpenOrCreate);
                    await img.SaveAsGifAsync(f3);
                    using var f4 = new FileStream(@".\test\async_stream_enc.gif", FileMode.OpenOrCreate);
                    await img.SaveAsGifAsync(f4, new SixLabors.ImageSharp.Formats.Gif.GifEncoder());
                }

                {
                    img.SaveAsJpeg(@".\test\norm_name.jpg");
                    img.SaveAsJpeg(@".\test\norm_name_enc.jpg", new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder());
                    await img.SaveAsJpegAsync(@".\test\async_name.jpg");
                    await img.SaveAsJpegAsync(@".\test\async_name_enc.jpg", new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder());
                    using var f1 = new FileStream(@".\test\norm_stream.jpg", FileMode.OpenOrCreate);
                    img.SaveAsJpeg(f1);
                    using var f2 = new FileStream(@".\test\norm_stream_enc.jpg", FileMode.OpenOrCreate);
                    img.SaveAsJpeg(f2, new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder());
                    using var f3 = new FileStream(@".\test\async_stream.jpg", FileMode.OpenOrCreate);
                    await img.SaveAsJpegAsync(f3);
                    using var f4 = new FileStream(@".\test\async_stream_enc.jpg", FileMode.OpenOrCreate);
                    await img.SaveAsJpegAsync(f4, new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder());
                }

            }
        }
    }

### CODE REVIEW

**Comment by pekspro** [comment]
Sure @antonfirsov, I would like to see some unit test too on this :-) Just give me some guidance and I fix it :-)

As I see it, it would be nice if the extension methods worked with an interface instead of Image. But it is quit trick right now because of lines like this:

       encoder ?? source.GetConfiguration().ImageFormatsManager.FindEncoder(BmpFormat.Instance));

`GetConfiguration` does not return an interface, and `ImageFormatsManager` is also not an interface.

**Comment by pekspro** [comment]
@antonfirsov , what if I created unit test like this?

        public class BmpImageExtensions
        {
            [Fact]
            public async Task SaveAsBmpAsync_Path()
            {
                string dir = TestEnvironment.CreateOutputDirectory(nameof(BmpImageExtensions));
                string file = Path.Combine(dir, "SaveAsBmpAsync_Path.bmp");

                using (var image = new Image<Rgba32>(10, 10))
                {
                    await image.SaveAsBmpAsync(file);
                }

                using (Image.Load(file, out IImageFormat mime))
                {
                    Assert.Equal("image/bmp", mime.DefaultMimeType);
                }
            }

            [Fact]
            public async Task SaveAsBmpAsync_Path_Encoder()
            {
                string dir = TestEnvironment.CreateOutputDirectory(nameof(BmpImageExtensions));
                string file = Path.Combine(dir, "SaveAsBmpAsync_Path_Encooder.bmp");

                using (var image = new Image<Rgba32>(10, 10))
                {
                    await image.SaveAsBmpAsync(file, new BmpEncoder());
                }

                using (Image.Load(file, out IImageFormat mime))
                {
                    Assert.Equal("image/bmp", mime.DefaultMimeType);
                }
            }

            [Fact]
            public async Task SaveAsBmpAsync_Stream()
            {
                using var memoryStream = new MemoryStream();

                using (var image = new Image<Rgba32>(10, 10))
                {
                    await image.SaveAsBmpAsync(memoryStream);
                }

                memoryStream.Position = 0;

                using (Image.Load(memoryStream, out IImageFormat mime))
                {
                    Assert.Equal("image/bmp", mime.DefaultMimeType);
                }
            }

            [Fact]
            public async Task SaveAsBmpAsync_Stream_Encoder()
            {
                using var memoryStream = new MemoryStream();

                using (var image = new Image<Rgba32>(10, 10))
                {
                    await image.SaveAsBmpAsync(memoryStream, new BmpEncoder());
                }

                memoryStream.Position = 0;

                using (Image.Load(memoryStream, out IImageFormat mime))
                {
                    Assert.Equal("image/bmp", mime.DefaultMimeType);
                }
            }
        }

**Comment by antonfirsov** [comment]
@pekspro perfect, thanks! Go ahead!

**Comment by JimBobSquarePants** [comment]
Perfect @pekspro Thanks so much for doing this!

**Pull request merged**
