### PR TITLE
Fix missing "using PixelFormats" line in Readme example

### PR DESCRIPTION
**Pull request by tonygameplan**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- (N/A) I have provided test coverage for my change (where applicable)

### Description

"<Rgba32>" does not appear to be defined without the "using SixLabors.ImageSharp.PixelFormats;" line and causes a "The type or namespace name 'Rgba32' could not be found (are you missing a using directive or an assembly reference?) (CS0246)" error to occur. This change fixes the issue by adding the PixelFormats line to the initial dependencies section.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Thanks for this. We actually need to change the sample slightly though since we introduced the new non generic syntax in #904.

The sample should be:

```
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

// Image.Load(string path) is a shortcut for the default type. 
// Other pixel formats use Image.Load<TPixel>(string path))
using (Image image = Image.Load("foo.jpg"))
{
    image.Mutate(x => x
         .Resize(image.Width / 2, image.Height / 2)
         .Grayscale());
    image.Save("bar.jpg"); // Automatic encoder selected based on extension.
}
```

**Comment by antonfirsov** [comment]
It could be a source of confusion to use the  `Image image = ...` declaration here, since the class is only present in the nightlies at the moment. Maybe we should replace it with `var` for now.

**Comment by JimBobSquarePants** [comment]
@antonfirsov You're making me twitchy reading that 😄 `var` without an explicit declaration on the right hand side. Naughty!

**Comment by antonfirsov** [comment]
> @antonfirsov You're making me twitchy reading that 😄 var without an explicit declaration on the right hand side. Naughty!

Not if you look at it as a sample code for Nightly / RC1 versions 😄 It might be also an option to merge this PR as is, and fix the samples before releasing RC1.

**Comment by JimBobSquarePants** [comment]
Let's do that then. @tonygameplan please ignore all our chatter; I'll get this updated and merged now. Cheers! 👍

**Pull request merged**
