### PR TITLE
Handle negative x offset for DrawImage

### LINKED ISSUE #252: DrawImage doesn't overlay the "x" position properly if "x" is < 0
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using  DrawImage with a negative X position,  it seems that the rightmost part of the image were cropped instead of moving the image to the left (negative position relative to parent image).

### Steps to Reproduce

Just try to set negative location in the X position like below:

                        image
                            .DrawImage(image2, size, new Point(-31, 62), GraphicsOptions.Default)
                            .Save(stream, new PngEncoder()); 

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00140
- Other ImageSharp packages and versions: ImageSharp.Drawing 1.0.0-alpha9-00135
- Environment (Operating system, version and so on):  W10 64bit
- .NET Framework version: WPF .Net 4.6

- Additional information:
drawimage

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
This PR fixes #252 where we weren't correctly handling negative x-offset values when drawing images.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
@tocsoft I'll get a test added in the morning. I have a pretty good idea how to do so.

**Comment by tocsoft** [comment]
hmm.. not sure about those tests, at the very least they seem really heavy (loading in real images instead of makes a couple of calculated/patterned ones). I'll have to take a closer look this evening.

**Comment by JimBobSquarePants** [comment]
Good thinking. Would certainly save overheads.

**Comment by JimBobSquarePants** [comment]
I'm gonna merge this now as I want to keep the ball rolling.

**Pull request merged**
