### PR TITLE
[WIP] Execute tests against .NET Core 2.1

### LINKED ISSUE #459: Add support for .NET Core 2.1
### Description
I've recently upgrade my system to ASP.NET Core 2.1.0-preview2-30045
This libraries are using System.Memory 4.5.0-preview2-26202-05

After update I'm not able to load image any more:
`using (var image = Image.Load<Rgba32>(pictureDataBytes, new PngDecoder()))`

this is throwing exception:
```
System.MethodAccessException: Attempt by method 'SixLabors.ImageSharp.Formats.Png.Filters.SubFilter.Decode(System.Span`1<Byte>, Int32)' to access method 'System.Span`1<System.Byte>.DangerousGetPinnableReference()' failed.
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.DecodePixelData[TPixel](Stream compressedStream, ImageFrame`1 image)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass43_0`1.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream, IImageDecoder decoder)
   at SixLabors.ImageSharp.Image.Load[TPixel](Byte[] data, IImageDecoder decoder)
```

### Steps to Reproduce
use ` System.Memory` `4.5.0-preview2-26202-05` and try to load PNG image.

### System Configuration

- ImageSharp version: 1.0.0-beta0002
- Other ImageSharp packages and versions: 1.0.0-beta0002
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.6.2
- Additional information:

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites
- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Running tests against .NET Core 2.1 should guarantee our support for that target framework. This should resolve #459 enabling the release of beta-4.

### Consequenses
~As far as I understand, It's not possible to use  .NET Core 2.1 RC1 with Visual Studion earlier than **2017 PRE**, so merging this PR will result in false build failures on earlier versions.~

**UPDATE 1:**
I had to add `global.json` directly referencing RC1 SDK to make the whole thing work. Using the earlier VS2017 is fine, but having [sdk 2.1.300-rc1](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1) installed would be a prerequisite now for every contributor after the merge.

**UPDATE 2:**
I just realized that the RC1 SDK is [not yet available on chocolatey](https://chocolatey.org/packages/dotnetcore-sdk). We should wait or find another way to install it on appveyor.

### CODE REVIEW

**Comment by antonfirsov** [comment]
Damn.
I have a [repository for hacking AppVeyor](https://github.com/antonfirsov/AppVeyorDotnetSandbox) gonna continue my experiments here.

**Comment by JimBobSquarePants** [comment]
Haha there’s plenty of them already in the codebase.

**Comment by antonfirsov** [comment]
Ok, it's mission impossible, the tooling bug won.

Gonna redefine the purpose of this PR:
Let's just add the 2.1 setup for now to enable manual execution, disable 2.1 test execution on CI, and define 2.1 test execution to be part of our (self)review process.

We can release beta4 this way. The bug is gonna be fixed in rc2. According to @brianpopow, it's already fixed in nightlies. (Big thanks for him for pointing my attention to dotnet/cli#9240 a few days ago!)

**Comment by JimBobSquarePants** [comment]
@antonfirsov That sounds like a plan to me. Let’s do it :+1:

**Comment by antonfirsov** [comment]
Ok, we need to fix travis here (by disabling 2.1/moving back to 2.0) + we should reference the newst sl.drawing package to fix the drawing artifact issues.

Let's hope we can do it by let's say Wednessday. I'm AFK until tomorrow evening.

**Comment by antonfirsov** [comment]
I'm closing this in favor of #585

**Pull request closed without merging**
