### PR TITLE
Replace CoreCompat.System.Drawing with System.Drawing.Common

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
`CoreCompat.System.Drawing` is now obsolete and should be replaced with official libraries.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Answers on a postcard guys. This works locally and on Travis.

Stacktrace is wonky nonsense. 

https://ci.appveyor.com/project/six-labors/imagesharp/build/1.0.0-PullRequest00457000722#L921

**Comment by antonfirsov** [comment]
@Toxantron the AvatarWithRoundedCorner project has been moved away from this repository. How should we change `.vscode/launch.json`?

**Comment by JimBobSquarePants** [comment]
@antonfirsov Thanks for the review and the extra cleanup. Keeping the samples in one location is best.

Happy to drop netstandard1.1 if everyone agrees. That loses NET 4.5.2 support but I think everyone should be on at least NET 4.6.1 anyway.

Re the failing tests, they're now passing on our Travis and AppVeyor builds but it comes down to equality comparers in the `IRgbWorkingSpace` implementations and the `Adapt` caller relying on them. I plan to have a good look at that. 

Re `.vscode/launch.json` I say point it at the benchmarks.

**Comment by antonfirsov** [comment]
Can we merge this after changing `.vscode/launch.json`? 

There are too much open PR-s now, makes it harder to manage conflicts.

**Pull request merged**
