### PR TITLE
opt out of mono on travis

### PR DESCRIPTION
**Pull request by SimonCropp**
looks like mono is not being used? if it is then close this

But if it isnt this PR will speed up your travis builds

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
@SimonCropp Looks like this won't work as it is.

```
System.DllNotFoundException : Unable to load DLL 'libgdiplus': The specified module could not be found.
```

https://travis-ci.org/SixLabors/ImageSharp/builds/602052654#L484

Updating to the latest System.Drawing.Common should hopefully fix it.
https://github.com/dotnet/core/issues/2746

**Comment by SimonCropp** [comment]
i pushed  System.Drawing.Common 4.6 to check

**Comment by JimBobSquarePants** [comment]
Same issue I'm afraid. I've cancelled the AppVeyor build to stop it blocking others.

**Comment by SimonCropp** [comment]
trying this https://github.com/dotnet/core/issues/2746#issuecomment-493571735

**Comment by JimBobSquarePants** [comment]
Fixed with #1082

**Pull request closed without merging**
