### PR TITLE
Add action to save Output Images for failed tests

### PR DESCRIPTION
**Pull request by AlexNDRmac**
- Added action to store images `tests/Images/ActualOutput/*` as build artifacts

### CODE REVIEW

**Comment by AlexNDRmac** [comment]
@antonfirsov - PR related to this [discussion](https://github.com/SixLabors/ImageSharp/pull/1403#discussion_r515634666)
If some job fail - this step store all images as build artifact to an action result.

**Comment by JimBobSquarePants** [comment]
@AlexNDRmac That's an awesome addition. Thanks!

**Comment by antonfirsov** [comment]
@AlexNDRmac thanks for pushing all these changes through!

**Comment by AlexNDRmac** [comment]
Feel free to ping me if you would have any issues with mac/linux :)

**Pull request merged**
